package Map;
import Entity.MineNode;
import Entity.Node;
import Entity.VillageNode;
import java.util.ArrayList;
/**
 * @program: Desert
 * @description: 游戏地图
 * @author: 宋丽
 * @create: 2020-09-11 11:47
 **/
public class GameMap {
    public GameMap() {
    }
    public static ArrayList<Node> getMapOne(){
        Node node1 = new Node(1);
        Node node2 = new Node(2);
        Node node3 = new Node(3);
        Node node4 = new Node(4);
        Node node5 = new Node(5);
        Node node6 = new Node(6);
        Node node7 = new Node(7);
        Node node8 = new Node(8);
        //Node node9 = new Node(9);
        Node node9 = new MineNode(9);
        Node node10 = new Node(10);
        Node node11 = new Node(11);
        //Node node12 = new MineNode(12);
        Node node12 = new Node(12);
        Node node13 = new Node(13);
        //Node node14 = new Node(14);
        Node node14 = new VillageNode(14);
        //Node node15 = new VillageNode(15);
        Node node15 = new Node(15);
        Node node16 = new Node(16);
        Node node17 = new Node(17);
        //Node node18 = new Node(18);
        Node node18 = new MineNode(18);
        Node node19 = new Node(19);
        Node node20 = new Node(20);
        Node node21 = new Node(21);
        Node node22 = new Node(22);
        Node node23 = new Node(23);
        Node node24 = new Node(24);
        Node node25 = new Node(25);
        Node node26 = new Node(26);
        Node node27 = new Node(27);
        Node node28 = new Node(28);
        Node node29 = new Node(29);
        Node node30 = new MineNode(30);
        Node node31 = new Node(31);
        Node node32 = new Node(32);
        Node node33 = new Node(33);
        Node node34 = new Node(34);
        Node node35 = new Node(35);
        Node node36 = new Node(36);
        Node node37 = new Node(37);
        Node node38 = new VillageNode(38);
        Node node39 = new Node(39);
        Node node40 = new Node(40);
        Node node41 = new Node(41);
        Node node42 = new Node(42);
        Node node43 = new Node(43);
        Node node44 = new Node(44);
        Node node45 = new Node(45);
        Node node46 = new Node(46);
        Node node47 = new Node(47);
        Node node48 = new Node(48);
        Node node49 = new Node(49);
        Node node50 = new Node(50);
        Node node51 = new Node(51);
        Node node52 = new Node(52);
        Node node53 = new Node(53);
        Node node54 = new Node(54);
        Node node55 = new MineNode(55);
        Node node56 = new Node(56);
        Node node57 = new Node(57);
        Node node58 = new Node(58);
        Node node59 = new Node(59);
        Node node60 = new Node(60);
        Node node61 = new Node(61);
        Node node62 = new Node(62);
        Node node63 = new Node(63);
        Node node64 = new Node(64);
        /*
        node1.setNextNode(new Node[]{node1,node2,node25});
        node2.setNextNode(new Node[]{node1,node2,node3});
        node3.setNextNode(new Node[]{node3,node2,node4,node25});
        node4.setNextNode(new Node[]{node4,node3,node5,node24,node25});
        node5.setNextNode(new Node[]{node5,node4,node6,node24});
        node6.setNextNode(new Node[]{node6,node5,node7,node23,node24});
        node7.setNextNode(new Node[]{node7,node6,node8,node22});
        node8.setNextNode(new Node[]{node8,node9,node7,node22});
        node9.setNextNode(new Node[]{node9,node8,node22,node21,node17,node16,node15,node10});
        node10.setNextNode(new Node[]{node10,node9,node15,node13,node11});
        node11.setNextNode(new Node[]{node11,node10,node12,node13});
        node12.setNextNode(new Node[]{node11,node13,node14,node12});
        node13.setNextNode(new Node[]{node13,node11,node12,node14,node15});
        node14.setNextNode(new Node[]{node14,node12,node13,node15,node16});
        node15.setNextNode(new Node[]{node15,node9,node10,node13,node14,node16});
        node16.setNextNode(new Node[]{node16,node14,node15,node9,node17,node18});
        node17.setNextNode(new Node[]{node17,node16,node9,node21,node18});
        node18.setNextNode(new Node[]{node18,node16,node17,node20,node19});
        node19.setNextNode(new Node[]{node19,node18,node20});
        node20.setNextNode(new Node[]{node20,node19,node18,node21});
        node21.setNextNode(new Node[]{node21,node20,node17,node9,node22,node23,node27});
        node22.setNextNode(new Node[]{node22,node9,node8,node7,node23,node21});
        node23.setNextNode(new Node[]{node23,node21,node22,node6,node24,node26});
        node24.setNextNode(new Node[]{node23,node6,node5,node4,node25,node26});
        node25.setNextNode(new Node[]{node25,node24,node4,node3,node1,node26});
        node26.setNextNode(new Node[]{node26,node27,node23,node24,node25});
        node27.setNextNode(new Node[]{node27,node21,node26});
        */
        node1.setNextNode(new Node[]{node2,node25});
        node2.setNextNode(new Node[]{node1,node3});
        node3.setNextNode(new Node[]{node2,node4,node25});
        node4.setNextNode(new Node[]{node3,node5,node24,node25});
        node5.setNextNode(new Node[]{node4,node6,node24});
        node6.setNextNode(new Node[]{node5,node7,node23,node24});
        node7.setNextNode(new Node[]{node6,node8,node22});
        node8.setNextNode(new Node[]{node9,node7,node22});
        node9.setNextNode(new Node[]{node8,node22,node21,node17,node16,node15,node10});
        node10.setNextNode(new Node[]{node9,node15,node13,node11});
        node11.setNextNode(new Node[]{node10,node12,node13});
        node12.setNextNode(new Node[]{node11,node13,node14});
        node13.setNextNode(new Node[]{node11,node12,node14,node15});
        node14.setNextNode(new Node[]{node12,node13,node15,node16});
        node15.setNextNode(new Node[]{node9,node10,node13,node14,node16});
        node16.setNextNode(new Node[]{node14,node15,node9,node17,node18});
        node17.setNextNode(new Node[]{node16,node9,node21,node18});
        node18.setNextNode(new Node[]{node16,node17,node20,node19});
        node19.setNextNode(new Node[]{node18,node20});
        node20.setNextNode(new Node[]{node19,node18,node21});
        node21.setNextNode(new Node[]{node20,node17,node9,node22,node23,node27});
        node22.setNextNode(new Node[]{node9,node8,node7,node23,node21});
        node23.setNextNode(new Node[]{node21,node22,node6,node24,node26});
        node24.setNextNode(new Node[]{node23,node6,node5,node4,node25,node26});
        node25.setNextNode(new Node[]{node24,node4,node3,node1,node26});
        node26.setNextNode(new Node[]{node27,node23,node24,node25});
        node27.setNextNode(new Node[]{node21,node26});
        ArrayList<Node> list = new ArrayList<>();
        list.add(node1);
        list.add(node2);
        list.add(node3);
        list.add(node4);
        list.add(node5);
        list.add(node6);
        list.add(node7);
        list.add(node8);
        list.add(node9);
        list.add(node10);
        list.add(node11);
        list.add(node12);
        list.add(node13);
        list.add(node14);
        list.add(node15);
        list.add(node16);
        list.add(node17);
        list.add(node18);
        list.add(node19);
        list.add(node20);
        list.add(node21);
        list.add(node22);
        list.add(node23);
        list.add(node24);
        list.add(node25);
        list.add(node26);
        list.add(node27);
        list.add(node28);
        list.add(node29);
        list.add(node30);
        list.add(node31);
        list.add(node32);
        list.add(node33);
        list.add(node34);
        list.add(node35);
        list.add(node36);
        list.add(node37);
        list.add(node38);
        list.add(node39);
        list.add(node40);
        list.add(node41);
        list.add(node42);
        list.add(node43);
        list.add(node44);
        list.add(node45);
        list.add(node46);
        list.add(node47);
        list.add(node48);
        list.add(node49);
        list.add(node50);
        list.add(node51);
        list.add(node52);
        list.add(node53);
        list.add(node54);
        list.add(node55);
        list.add(node56);
        list.add(node57);
        list.add(node58);
        list.add(node59);
        list.add(node60);
        list.add(node61);
        list.add(node62);
        list.add(node63);
        list.add(node64);
        return list;
    }

    public static ArrayList<Node> getMapFive(){
        Node node1 = new Node(1);
        Node node2 = new Node(2);
        Node node3 = new Node(3);
        Node node4 = new Node(4);
        Node node5 = new Node(5);
        Node node6 = new Node(6);
        Node node7 = new Node(7);
        Node node8 = new Node(8);
        //Node node9 = new Node(9);
        Node node9 = new MineNode(9);
        Node node10 = new Node(10);
        Node node11 = new Node(11);
        //Node node12 = new MineNode(12);
        Node node12 = new Node(12);
        Node node13 = new Node(13);

        node1.setNextNode(new Node[]{node2,node5});
        node2.setNextNode(new Node[]{node1,node3,node4});
        node3.setNextNode(new Node[]{node2,node4,node8,node9});
        node4.setNextNode(new Node[]{node1,node2,node3,node5,node6,node7});
        node5.setNextNode(new Node[]{node4,node6,node1});
        node6.setNextNode(new Node[]{node5,node7,node12,node13});
        node7.setNextNode(new Node[]{node6,node4,node12,node11});
        node8.setNextNode(new Node[]{node9,node3});
        node9.setNextNode(new Node[]{node8,node3,node11,node10});
        node10.setNextNode(new Node[]{node9,node13,node11});
        node11.setNextNode(new Node[]{node10,node12,node13,node7,node9});
        node12.setNextNode(new Node[]{node11,node13,node7,node6});
        node13.setNextNode(new Node[]{node11,node12,node10,node6});

        ArrayList<Node> list = new ArrayList<>();
        list.add(node1);
        list.add(node2);
        list.add(node3);
        list.add(node4);
        list.add(node5);
        list.add(node6);
        list.add(node7);
        list.add(node8);
        list.add(node9);
        list.add(node10);
        list.add(node11);
        list.add(node12);
        list.add(node13);

        return list;
    }
}
